# Generated by Django 3.2.5 on 2021-09-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('subject', models.IntegerField(max_length=8)),
                ('clss', models.IntegerField(max_length=8)),
                ('board', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_link', models.URLField(max_length=50)),
                ('language', models.IntegerField(max_length=8)),
            ],
            options={
                'db_table': 'scheduled_classes',
            },
        ),
    ]
